artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/d8b0cb3e3dd14baaae4526607a3285cb/artifacts
end_time: 1745687727300
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d8b0cb3e3dd14baaae4526607a3285cb
run_name: Default
run_uuid: d8b0cb3e3dd14baaae4526607a3285cb
source_name: ''
source_type: 4
source_version: ''
start_time: 1745687727237
status: 3
tags: []
user_id: mle-user
